//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRestriction
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> RestrictionId { get; set; }
    
        public virtual Restriction Restriction { get; set; }
        public virtual User User { get; set; }
    }
}
